name: "OpenWrt ImageBuilder"
description: "Build OpenWrt Image via the ImageBuilder"
author: aparcar
runs:
  using: 'composite'
  steps:
    - run: |
        echo "artifacts_dir=${ARTIFACTS_DIR:-$GITHUB_WORKSPACE}" >> "$GITHUB_OUTPUT"
        echo "repo_dir=${REPO_DIR:-$GITHUB_WORKSPACE}" >> "$GITHUB_OUTPUT"
      shell: bash
      id: inputs
    - run: sudo chown -R 1000:1000 ${{ steps.inputs.outputs.artifacts_dir }} ${{ steps.inputs.outputs.repo_dir }}
      shell: bash
    -
      name: Set up Docker QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build Docker container image
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: imagebuilder
        context: ${{ github.action_path }}
        build-args: |
          CONTAINER
          ARCH
        cache-to: type=gha,mode=max,scope=${{ env.CONTAINER }}-${{ env.ARCH }}
        cache-from: type=gha,scope=${{ env.CONTAINER }}-${{ env.ARCH }}
        load: true

    - run: |
        docker run --rm \
          --env EXTRA_REPOS \
          --env NO_DEFAULT_REPOS \
          --env NO_LOCAL_REPOS \
          --env KEY_BUILD \
          --env KEY_BUILD_PUB \
          --env KEY_VERIFY \
          --env NO_SIGNATURE_CHECK \
          --env DISABLED_SERVICES \
          --env PROFILE \
          --env PACKAGES \
          --env ROOTFS_SIZE \
          -v ${{ steps.inputs.outputs.artifacts_dir }}:/artifacts \
          -v ${{ steps.inputs.outputs.repo_dir }}:/repo \
          imagebuilder
      shell: bash
    - run: sudo chown -R --reference=${{ steps.inputs.outputs.artifacts_dir }}/.. ${{ steps.inputs.outputs.artifacts_dir }}
      shell: bash
      if: always()
    - run: sudo chown -R --reference=${{ steps.inputs.outputs.repo_dir }}/.. ${{ steps.inputs.outputs.repo_dir }}
      shell: bash
      if: always()
