name: Test

on:
  pull_request:

jobs:
  build:
    name: Test ${{ matrix.release }}-${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - master
          - 24.10.1
          - 23.05.5
        target:
          - 'armsr/armv8'
          - 'ipq806x/generic'
          - 'ath79/nand'
          - 'x86/64'

    steps:
      - uses: actions/checkout@v6

      - name: Add test directories
        run: mkdir artifacts repo

      - name: Build
        uses: ./
        env:
          TARGET: ${{ matrix.target }}
          VERSION: ${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          REPO_DIR: ${{ github.workspace }}/repo
          PACKAGES: vim privoxy

      - name: Verify images saved
        run: find artifacts/bin/targets/${{ matrix.target }}/ -maxdepth 1 -type f | grep .
